### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by brutalzinn** [makeratplay/VirtualMeetingMonitor#5]
Thanks to sharing this awesome project. I'm using this project base to detect my zoom calls and i pretend to integrate with google sheets to handler my hours [My repository](https://github.com/brutalzinn/zoom-monitor-googlesheets) 

If i broke some rules or licenses, please tell me. #thanksalot

**Comment by makeratplay** [comment]
That's awesome. Thanks for sharing.

Regards,
Michael
